package com.github.appreciated.quickstart.material.login;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.*;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class MaterialLogin extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class LoginDesign extends VerticalLayout {
    protected Label title;
    protected TabSheet tabs;
    protected VerticalLayout loginForm;
    protected FormLayout registrationFormLayout;
    protected TextField username;
    protected PasswordField password;
    protected Button loginButton;
    protected Button registerButton;
    protected HorizontalLayout bottomBarWrapper;

    public LoginDesign() {
        Design.read(this);
    }
}
