package com.github.appreciated.quickstart.material.legals;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class MaterialLogin extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ImprintDesign extends VerticalLayout {
    protected FormLayout senderAddress;
    protected Label name;
    protected Label street;
    protected Label address;
    protected FormLayout contact;
    protected Label phone;
    protected Label mail;

    public ImprintDesign() {
        Design.read(this);
    }
}
