package com.github.appreciated.quickstart.base.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ProgressStepDesign extends HorizontalLayout {
    protected HorizontalLayout stepNameWrapper;
    protected Label stepNumber;
    protected Label stepName;

    public ProgressStepDesign() {
        Design.read(this);
    }
}
