package com.github.appreciated.quickstart.material;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.*;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class MaterialLogin extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class DesktopNavigationDesign extends VerticalLayout {
    protected HorizontalLayout iconContainer;
    protected Label title;
    protected MenuBar user;
    protected MenuBar navigationMenu;
    protected MenuBar contextButtons;
    protected HorizontalLayout searchBarWrapper;
    protected HorizontalLayout menuElements;
    protected VerticalLayout pageWrapper;
    protected TextField searchBar;
    protected HorizontalLayout contextButtonWrapper;
    protected HorizontalLayout componentHolder;
    protected Label containerLabel;

    public DesktopNavigationDesign() {
        Design.read(this);
    }

}
