package com.github.appreciated.quickstart.material;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.*;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class MaterialLogin extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MobileNavigationDesign extends AbsoluteLayout {
    protected Button menuButton;
    protected VerticalLayout componentHolder;
    protected VerticalLayout contextButtonContainer;
    protected VerticalLayout contextButtonWrapper;
    protected VerticalLayout smallContextButtonContainer;
    protected Button floatingButton;
    protected HorizontalLayout menuWrapper;
    protected HorizontalLayout menuElements;
    protected VerticalLayout navigationElements;
    protected Button showSearchbarButton;
    protected TextField searchbar;
    protected HorizontalLayout menubarWrapper;
    protected HorizontalLayout searchbarWrapper;
    protected VerticalLayout menu;
    protected HorizontalLayout logoutWrapper;
    protected Button logout;

    public MobileNavigationDesign() {
        Design.read(this);
    }


}
